### ISSUE TITLE
Test PIRLNav with ros4vsn

### ISSUE THREAD

**Issue by leyuan-sun** [gramuah/vsn_rr#1]
Thanks for the nice work. Is threre some guidance about implementing PIRLNav with ROS4VSN except the random walking in this repo.?

**Comment by rlopezsastre** [comment]
Yes, sure.
We have prepared a tutorial for this (see examples folder)
You can access it at the following [link](https://github.com/gramuah/ros4vsn/tree/main/examples/PIRLNav).
Hope this helps.

**Comment by leyuan-sun** [comment]
Thanks for your reply, I have seen the READEME in your example folder, it seems that it is the process about how to run PIRLNav in habitat simulator, but I would like to try PILRNav in real robot.

For example, where is the code about PILRNav program subscribe the image topic? Do we need to implement by ourselves?

**Comment by CarlosGual** [comment]
Hello @rginjapan, we are working to include a functional PIRLNav example. Sadly we did not include it properly in the examples.

Thank you for pointing it out.

**Comment by CarlosGual** [comment]
@rginjapan we included the instructions and the code to deploy pirlnav model using our library ros4vsn. You can find everything [here](https://github.com/gramuah/ros4vsn?tab=readme-ov-file#launching-the-project-with-pirlnav). Let us know if you experience more problems.

**Comment by leyuan-sun** [comment]
Thansk for updating, I will try later. I have checked the update readme, in Step 5: is it necessary to download the HM3D dataset even I just want to try on real robot?

**Comment by CarlosGual** [comment]
@rginjapan I fear so. The pirlnav agent set up process needs the data, if not it fails.

**Comment by leyuan-sun** [comment]
I do not understand why the HM3D dataset is necessary for deploy PIRLNav on real robot. Besides, the last step is not clear for me 

> Copy the content inside our folder [ros4pirlnav]

(https://github.com/gramuah/ros4vsn/blob/main/examples/pirlnav/ros4pirlnav) in [catkin_ws\vsn](https://github.com/gramuah/ros4vsn/blob/main/catkin_ws/src/vsn/scripts) .

e.g. where shoud I put the pretrained model, what command to use to run the PRTLNav?

**Comment by rflor01** [comment]
Apologies for any inconvenience caused. The README.md has been updated to provide more comprehensive information.

Additionally, I acknowledge that the integration of the PIRLNav model into real-world scenarios may seem confusing, particularly regarding the necessity of the HM3D dataset. It is important to note that this information is not utilized during the model's runtime. However, due to the interdependencies between the PIRLNav model and Habitat, it has been designed without breaking this internal dependencies.

Thanks to the capabilities of ROS, it is possible to execute the model on one server while the Turtlebot exclusively runs the movement server packages. Both can be seamlessly connected to the same LAN Network.

I trust that this clarification addresses any concerns.

**Comment by rflor01** [comment]
We have addressed this, @leyuan-sun. The pirlnav example no longer depends on the HM3D dataset, which resolves this issue. Thank you for your attention.
